org: rudixlab
app: rudixlab

service: dynamodbone
plugins:
    - serverless-domain-manager
custom:
    customDomain:
        domainName: 'rudixlab.com'
        basePath: ''
        stage: ${self:provider.stage}
        createRoute53Record: true
provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: eu-central-1
    iamRoleStatements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
              - dynamodb:DescribeTable
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - s3:PutObject
              - s3:GetObject
          Resource: 'arn:aws:dynamodb:eu-central-1:*:*'
functions:
    app:
        handler: server.handler
        memorySize: 512
        events:
            - http: ANY /
            - http: 'ANY {proxy+}'
