app: rudixlab

service: dynamodbone
plugins:
    - serverless-domain-manager
custom:
    customDomain:
        domainName: 'rudixlab.com'
        basePath: ''
        stage: ${self:provider.stage}
        createRoute53Record: true
provider:
    logs:
        - accessLogging: false
        - executionLogging: false
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: eu-central-1
    timeout: 10
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:DescribeTable
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
          Resource:
              - arn:aws:dynamodb:eu-central-1:*:*
        - Effect: Allow
          Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
          Resource:
              - 'arn:aws:s3:::'
functions:
    app:
        disableLogs: true
        handler: server.handler
        memorySize: 512
        events:
            - http: ANY /
            - http: 'ANY {proxy+}'
