org: rudixlab
app: myapp

service: dynamo

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: eu-central-1
    iamRoleStatements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
              - dynamodb:DescribeTable
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
          Resource: 'arn:aws:dynamodb:eu-central-1:*:*'
functions:
    app:
        handler: server.handler
        events:
            - http: ANY /
            - http: 'ANY {proxy+}'
