name: S3 Build
on:
    pull_request:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Replace homepage
              run: rm -rf .git && rm -rf src && rm -rf *.js
            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read
              env:
                  URL: 'http://rudixgit.github.io/freeteenpicsandmovies/'
                  AWS_S3_BUCKET: 'img.rudixlab.com'
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: 'eu-west-1' # optional: defaults to us-east-1
                  #SOURCE_DIR: 'public' # optional: defaults to entire repository
